name: e2e
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # install NPM dependencies, Cypress and run tests
      # https://github.com/cypress-io/github-action
      - name: Run Tests 🧪
        uses: cypress-io/github-action@v2
        with:
          start: 'yarn web'
          wait-on: 'http://localhost:19006'
